# Generated by Django 4.1.7 on 2023-06-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("Class", models.IntegerField()),
                ("section", models.CharField(max_length=1)),
                ("logo", models.URLField()),
                ("description", models.TextField()),
                ("votes", models.IntegerField()),
            ],
        ),
    ]
