# Generated by Django 4.1.7 on 2023-06-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="gender",
            field=models.CharField(default="Female", max_length=6),
        ),
    ]
