# Generated by Django 4.1.7 on 2023-06-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0002_candidate_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="image",
            field=models.ImageField(default=None, upload_to=""),
            preserve_default=False,
        ),
    ]
