# Generated by Django 4.1.7 on 2023-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0004_alter_candidate_image_alter_candidate_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="image",
            field=models.ImageField(upload_to="stat"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="logo",
            field=models.ImageField(upload_to="stat"),
        ),
    ]
