# Generated by Django 4.1.7 on 2023-06-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_candidate_image_alter_candidate_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
