# Generated by Django 4.1.7 on 2023-06-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_alter_candidate_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='logo',
        ),
    ]
