# Generated by Django 4.1.7 on 2023-06-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_remove_candidate_description_remove_candidate_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='logo',
            field=models.ImageField(default=None, upload_to='static/voting'),
            preserve_default=False,
        ),
    ]
